# Generated by Django 5.1.6 on 2025-03-19 11:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('C-Ice', 'Chocolate'), ('M-Ice', 'Mango'), ('S-Ice', 'Strawberry'), ('W-Ice', 'Vanilla')], max_length=6)),
            ],
        ),
    ]
