# Generated by Django 5.1.6 on 2025-03-21 17:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_person_avalible_ch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ice_reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.ImageField(upload_to='')),
                ('review', models.TextField()),
                ('ice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='app1.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='iceCartifcate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certifcate_no', models.TextField()),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('ice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Certifcate', to='app1.person')),
            ],
        ),
        migrations.CreateModel(
            name='stores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('location', models.TextField()),
                ('ice_type', models.ManyToManyField(related_name='store', to='app1.person')),
            ],
        ),
    ]
