# Generated by Django 5.1.6 on 2025-03-21 17:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_ice_reviews_icecartifcate_stores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icecartifcate',
            name='ice',
        ),
        migrations.AlterField(
            model_name='stores',
            name='ice_type',
            field=models.ManyToManyField(related_name='stores', to='app1.person'),
        ),
        migrations.AlterField(
            model_name='stores',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='IceCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_no', models.CharField(max_length=100)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('ice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='app1.person')),
            ],
        ),
        migrations.CreateModel(
            name='IceReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('review', models.TextField()),
                ('ice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app1.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ice_reviews',
        ),
        migrations.DeleteModel(
            name='iceCartifcate',
        ),
    ]
