# Generated by Django 5.1.7 on 2025-03-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_person_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.CharField(choices=[('C-Ice', 'Chocolate'), ('M-Ice', 'Mango'), ('S-Ice', 'Strawberry'), ('W-Ice', 'Vanilla'), ('salted-Ice', 'Salted Caramel'), ('Mint_Ice', 'Mint Chocolate Chip'), ('Pineapple Ice', 'Pineapple Coconu'), ('cookies Ice', 'Cookies & Cream'), ('Blue Barry', 'Blue Barry')], max_length=14),
        ),
    ]
