# Generated by Django 5.1.7 on 2025-03-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_icereviews_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='order_id',
            field=models.TextField(default=0),
        ),
    ]
