# Generated by Django 5.1.7 on 2025-03-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_customers_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='order_id',
            field=models.TextField(default=0),
        ),
    ]
