# Generated by Django 5.1.6 on 2025-03-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_icereviews_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecertificate',
            name='commission',
            field=models.TextField(default=''),
        ),
    ]
