# Generated by Django 5.1.6 on 2025-03-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_icecertificate_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecertificate',
            name='logo',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
