# Generated by Django 5.1.6 on 2025-04-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0025_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="cardno",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
