# Generated by Django 5.1.6 on 2025-04-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0026_card_cardno"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="amount",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
