# Generated by Django 5.1.6 on 2025-03-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_person_avalible_ch_person_dec_person_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avalible_ch',
            field=models.IntegerField(default=0),
        ),
    ]
