# Generated by Django 5.1.7 on 2025-03-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_person_type_customers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='ice',
            new_name='ice_name',
        ),
    ]
