# Generated by Django 5.1.7 on 2025-03-25 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_rename_person_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icereviews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.customers'),
        ),
    ]
