# Generated by Django 5.1.7 on 2025-03-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_customers_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='icereviews',
            name='order_id',
            field=models.TextField(default=0),
        ),
    ]
