# Generated by Django 5.1.6 on 2025-03-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_icecertificate_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecertificate',
            name='logo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
