# Generated by Django 5.1.6 on 2025-03-26 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_icecertificate_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icecertificate',
            old_name='logo',
            new_name='image',
        ),
    ]
