# Generated by Django 5.1.6 on 2025-04-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0022_rename_logo_icecertificate_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customers",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
