# Generated by Django 5.1.6 on 2025-04-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0023_customers_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customers",
            name="bill",
            field=models.IntegerField(default=0),
        ),
    ]
