# Generated by Django 5.1.6 on 2025-04-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0024_customers_bill"),
    ]

    operations = [
        migrations.CreateModel(
            name="card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nameoncard", models.TextField()),
                ("cvc", models.IntegerField()),
            ],
        ),
    ]
